name: Default build workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Run-echo-command-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: default push
        run: echo "Testing workflow"
        shell: bash
