name: "Windows Build"

on: 
  push:
    tags: 
      - "lab-automata/v*"

env:
  lab_automata_sol_path: LabAutomata/LabAutomata.csproj

jobs:
  deploy:
    runs-on: windows-latest
    steps: 
      - name: Outout build started
        run: echo "Running LabAutomata build"
      
      - name: Checkout v4
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1

      - name: Restore dotnet packages at root UI path
        run: dotnet restore ${{env.lab_automata_sol_path}}

      - name: Output building application
        shell: bash
        run: echo "Building application..."

      - name: Build the WPF application
        run: dotnet build ${{env.lab_automata_sol_path}} -c RELEASE --no-restore

      - name: Output publishing application      
        shell: bash
        run: echo "Publishing application..."
        
      - name: Publish the WPF application
        run: dotnet publish ${{env.lab_automata_sol_path}} -c RELEASE --self-contained -r win-x64 -p:PublishSingleFile=true --no-build

      - name: Create a release action
        uses: actions/create-release@v1
        id: release
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: ${{github.ref}}
        
      - uses: csexton/release-asset-actions@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          pattern: LabAutomata\bin\Release\net8.0-windows\win-x64\publish/*.exe
          release-url: ${{steps.release.outputs.upload_url}}